
name: Deploy Fuga
on:
  release:
    types:
      - released
      - deleted

jobs:
  Deploy:
    name: Deploy
    runs-on: ubuntu-latest
    if: startsWith(github.event.release.tag_name, 'fuga')
    steps:
      - name: get latest tag name
        id: get-latest-tag
        env:
          GITHUB_RELEASE_API_ENDPOINT: https://api.github.com/repos/nao23/test/releases
        run: |
          curl -s -H "Authorization: token ${{ github.token }}" $GITHUB_RELEASE_API_ENDPOINT | jq '.'
          LATEST_TAG=$(curl -s -H "Authorization: token ${{ github.token }}" $GITHUB_RELEASE_API_ENDPOINT | jq -r '.[].tag_name' | grep "fuga" | sort -r | head -n1)
          echo "::set-output name=latest_tag::$LATEST_TAG"

      - name: test
        run: |
          echo ${{ github.event.release.tag_name }}
          echo ${{ steps.get-latest-tag.outputs.latest_tag }}
