name: Slack Notify (test)
on:
  push:
    branches:
      - specify-job-name 

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: |
          echo "Build"

      - uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          author_name: ''
          job_name: Build
          username: 'GitHub Actions'
          icon_emoji: ':github_octocat:'
          fields: repo,commit,author,job,workflow,took
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: ["web", "ope"]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install ecspresso
        uses: kayac/ecspresso@v1
        with:
          version: v1.0.0

      - name: Deploy
        run: |
          echo "Deploy"

      - uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          author_name: ''
          username: 'GitHub Actions'
          icon_emoji: ':github_octocat:'
          fields: repo,commit,author,job,workflow,took
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        if: always()
